version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: salemre-postgres
    environment:
      POSTGRES_DB: salemre
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: salemre-api
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: salemre
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your_jwt_secret
      JWT_EXPIRE: 30d
      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: salemre-client
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data: